### ISSUE TITLE
Add Season of Discovery Raids & Dungeons

### ISSUE THREAD

**Issue by dsvensson** [nanderson11/Atlas#14]

**Comment by nanderson11** [comment]
I think I covered what I could. I updated the player counts for Blackfathom Deeps, Gnomeregan, and Sunken Temple and the categories they fall under. I added a map of the exterior of Demon Fall Canyon (can't do interior maps now unfortunately). And I added maps for Storm Cliffs, Tainted Scar and Crystal Vale. I added an entry for Nightmare Grove (but no map since the instance isn't available yet).
